//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 03:44:23 PM EST 
//


package edu.cmu.cs.diamond.opendiamond.bundle;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * An option allowing the user to add example images to the search.  The
 * selected examples can then be included in a filter's blob argument by
 * specifying <examples>.  Produces an integer argument, probably not
 * actually useful, which gives the number of examples provided.
 *     
 * 
 * <p>Java class for ExampleOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExampleOption">
 *   &lt;complexContent>
 *     &lt;extension base="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}Option">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExampleOption")
public class ExampleOption
    extends Option
{


}
