//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 03:44:23 PM EST 
//


package edu.cmu.cs.diamond.opendiamond.bundle;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterBlobArgumentSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilterBlobArgumentSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="examples" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}FilterBlobExampleSpec" minOccurs="0"/>
 *         &lt;element name="member" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}FilterBlobMemberSpec" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="option" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}Filename" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilterBlobArgumentSpec", propOrder = {
    "examples",
    "members"
})
public class FilterBlobArgumentSpec {

    protected FilterBlobExampleSpec examples;
    @XmlElement(name = "member")
    protected List<FilterBlobMemberSpec> members;
    @XmlAttribute(name = "option")
    protected String option;
    @XmlAttribute(name = "data")
    protected String data;

    /**
     * 
     * Include an "examples" directory in the Zip archive which contains example
     * images in PNG format.  If present, the options section must include an
     * exampleOption.
     *         
     * 
     * @return
     *     possible object is
     *     {@link FilterBlobExampleSpec }
     *     
     */
    public FilterBlobExampleSpec getExamples() {
        return examples;
    }

    /**
     * Sets the value of the examples property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBlobExampleSpec }
     *     
     */
    public void setExamples(FilterBlobExampleSpec value) {
        this.examples = value;
    }

    /**
     * 
     * Include the specified member in the Zip archive.
     *           Gets the value of the members property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the members property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMembers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterBlobMemberSpec }
     * 
     * 
     */
    public List<FilterBlobMemberSpec> getMembers() {
        if (members == null) {
            members = new ArrayList<FilterBlobMemberSpec>();
        }
        return this.members;
    }

    /**
     * 
     * The name of the option specifying the filename of the blob argument.  Cannot
     * be present if member elements are specified.
     *       
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOption() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOption(String value) {
        this.option = value;
    }

    /**
     * 
     * The filename of the file containing the blob argument.  Cannot be present if
     * member elements are specified.
     *       
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

}
