//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 03:44:23 PM EST 
//


package edu.cmu.cs.diamond.opendiamond.bundle;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * A numeric option, displayed in the user interface as an editable numeric
 * field with increment/decrement buttons and a slider.  Produces an argument
 * formatted as an integer if possible, and as a double otherwise.
 *     
 * 
 * <p>Java class for NumberOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumberOption">
 *   &lt;complexContent>
 *     &lt;extension base="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}Option">
 *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="step" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *       &lt;attribute name="initiallyEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="disabledValue" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumberOption")
public class NumberOption
    extends Option
{

    @XmlAttribute(name = "default")
    protected Double _default;
    @XmlAttribute(name = "min")
    protected Double min;
    @XmlAttribute(name = "max")
    protected Double max;
    @XmlAttribute(name = "step")
    protected Double step;
    @XmlAttribute(name = "initiallyEnabled")
    protected Boolean initiallyEnabled;
    @XmlAttribute(name = "disabledValue")
    protected Double disabledValue;

    /**
     * 
     * The initial value of the option.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getDefault() {
        if (_default == null) {
            return  0.0D;
        } else {
            return _default;
        }
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDefault(Double value) {
        this._default = value;
    }

    /**
     * 
     * If specified, the minimum value of the option.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMin(Double value) {
        this.min = value;
    }

    /**
     * 
     * If specified, the maximum value of the option.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMax(Double value) {
        this.max = value;
    }

    /**
     * 
     * The step size for the scroll buttons in the user interface.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getStep() {
        if (step == null) {
            return  1.0D;
        } else {
            return step;
        }
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStep(Double value) {
        this.step = value;
    }

    /**
     * 
     * If specified, the option can be disabled by the user, and the initial
     * enablement is as specified.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInitiallyEnabled() {
        return initiallyEnabled;
    }

    /**
     * Sets the value of the initiallyEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInitiallyEnabled(Boolean value) {
        this.initiallyEnabled = value;
    }

    /**
     * 
     * The value returned if the option is disabled by the user.  Infinite and
     * NaN values are supported.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getDisabledValue() {
        if (disabledValue == null) {
            return  0.0D;
        } else {
            return disabledValue;
        }
    }

    /**
     * Sets the value of the disabledValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDisabledValue(Double value) {
        this.disabledValue = value;
    }

}
