//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 03:44:23 PM EST 
//


package edu.cmu.cs.diamond.opendiamond.bundle;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.cmu.cs.diamond.opendiamond.bundle package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Predicate_QNAME = new QName("http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1", "predicate");
    private final static QName _Codec_QNAME = new QName("http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1", "codec");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.cmu.cs.diamond.opendiamond.bundle
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PredicateSpec }
     * 
     */
    public PredicateSpec createPredicateSpec() {
        return new PredicateSpec();
    }

    /**
     * Create an instance of {@link FilterDependencyList }
     * 
     */
    public FilterDependencyList createFilterDependencyList() {
        return new FilterDependencyList();
    }

    /**
     * Create an instance of {@link Choice }
     * 
     */
    public Choice createChoice() {
        return new Choice();
    }

    /**
     * Create an instance of {@link FilterArgumentList }
     * 
     */
    public FilterArgumentList createFilterArgumentList() {
        return new FilterArgumentList();
    }

    /**
     * Create an instance of {@link ExampleOption }
     * 
     */
    public ExampleOption createExampleOption() {
        return new ExampleOption();
    }

    /**
     * Create an instance of {@link FilterBlobExampleSpec }
     * 
     */
    public FilterBlobExampleSpec createFilterBlobExampleSpec() {
        return new FilterBlobExampleSpec();
    }

    /**
     * Create an instance of {@link FilterArgumentSpec }
     * 
     */
    public FilterArgumentSpec createFilterArgumentSpec() {
        return new FilterArgumentSpec();
    }

    /**
     * Create an instance of {@link FilterList }
     * 
     */
    public FilterList createFilterList() {
        return new FilterList();
    }

    /**
     * Create an instance of {@link FilterSpec }
     * 
     */
    public FilterSpec createFilterSpec() {
        return new FilterSpec();
    }

    /**
     * Create an instance of {@link OptionGroup }
     * 
     */
    public OptionGroup createOptionGroup() {
        return new OptionGroup();
    }

    /**
     * Create an instance of {@link FilterThresholdSpec }
     * 
     */
    public FilterThresholdSpec createFilterThresholdSpec() {
        return new FilterThresholdSpec();
    }

    /**
     * Create an instance of {@link StringOption }
     * 
     */
    public StringOption createStringOption() {
        return new StringOption();
    }

    /**
     * Create an instance of {@link NumberOption }
     * 
     */
    public NumberOption createNumberOption() {
        return new NumberOption();
    }

    /**
     * Create an instance of {@link FilterBlobArgumentSpec }
     * 
     */
    public FilterBlobArgumentSpec createFilterBlobArgumentSpec() {
        return new FilterBlobArgumentSpec();
    }

    /**
     * Create an instance of {@link FilterDependencySpec }
     * 
     */
    public FilterDependencySpec createFilterDependencySpec() {
        return new FilterDependencySpec();
    }

    /**
     * Create an instance of {@link FileOption }
     * 
     */
    public FileOption createFileOption() {
        return new FileOption();
    }

    /**
     * Create an instance of {@link FilterBlobMemberSpec }
     * 
     */
    public FilterBlobMemberSpec createFilterBlobMemberSpec() {
        return new FilterBlobMemberSpec();
    }

    /**
     * Create an instance of {@link OptionList }
     * 
     */
    public OptionList createOptionList() {
        return new OptionList();
    }

    /**
     * Create an instance of {@link BooleanOption }
     * 
     */
    public BooleanOption createBooleanOption() {
        return new BooleanOption();
    }

    /**
     * Create an instance of {@link ChoiceOption }
     * 
     */
    public ChoiceOption createChoiceOption() {
        return new ChoiceOption();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PredicateSpec }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1", name = "predicate")
    public JAXBElement<PredicateSpec> createPredicate(PredicateSpec value) {
        return new JAXBElement<PredicateSpec>(_Predicate_QNAME, PredicateSpec.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PredicateSpec }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1", name = "codec")
    public JAXBElement<PredicateSpec> createCodec(PredicateSpec value) {
        return new JAXBElement<PredicateSpec>(_Codec_QNAME, PredicateSpec.class, null, value);
    }

}
