//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 03:44:23 PM EST 
//


package edu.cmu.cs.diamond.opendiamond.bundle;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OptionList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OptionList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="optionGroup" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}OptionGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="stringOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}StringOption"/>
 *           &lt;element name="numberOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}NumberOption"/>
 *           &lt;element name="booleanOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}BooleanOption"/>
 *           &lt;element name="choiceOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}ChoiceOption"/>
 *           &lt;element name="exampleOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}ExampleOption"/>
 *           &lt;element name="fileOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}FileOption"/>
 *         &lt;/choice>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OptionList", propOrder = {
    "optionGroups",
    "options"
})
public class OptionList {

    @XmlElement(name = "optionGroup")
    protected List<OptionGroup> optionGroups;
    @XmlElements({
        @XmlElement(name = "stringOption", type = StringOption.class),
        @XmlElement(name = "numberOption", type = NumberOption.class),
        @XmlElement(name = "booleanOption", type = BooleanOption.class),
        @XmlElement(name = "choiceOption", type = ChoiceOption.class),
        @XmlElement(name = "exampleOption", type = ExampleOption.class),
        @XmlElement(name = "fileOption", type = FileOption.class)
    })
    protected List<Option> options;

    /**
     * 
     * A list of options to be grouped into a labeled section within the user
     * interface.
     *           Gets the value of the optionGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptionGroup }
     * 
     * 
     */
    public List<OptionGroup> getOptionGroups() {
        if (optionGroups == null) {
            optionGroups = new ArrayList<OptionGroup>();
        }
        return this.optionGroups;
    }

    /**
     * Gets the value of the options property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the options property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringOption }
     * {@link NumberOption }
     * {@link BooleanOption }
     * {@link ChoiceOption }
     * {@link ExampleOption }
     * {@link FileOption }
     * 
     * 
     */
    public List<Option> getOptions() {
        if (options == null) {
            options = new ArrayList<Option>();
        }
        return this.options;
    }

}
