//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 03:44:23 PM EST 
//


package edu.cmu.cs.diamond.opendiamond.bundle;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OptionGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OptionGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="stringOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}StringOption"/>
 *         &lt;element name="numberOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}NumberOption"/>
 *         &lt;element name="booleanOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}BooleanOption"/>
 *         &lt;element name="choiceOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}ChoiceOption"/>
 *         &lt;element name="exampleOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}ExampleOption"/>
 *         &lt;element name="fileOption" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}FileOption"/>
 *       &lt;/choice>
 *       &lt;attribute name="displayName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OptionGroup", propOrder = {
    "options"
})
public class OptionGroup {

    @XmlElements({
        @XmlElement(name = "stringOption", type = StringOption.class),
        @XmlElement(name = "numberOption", type = NumberOption.class),
        @XmlElement(name = "booleanOption", type = BooleanOption.class),
        @XmlElement(name = "choiceOption", type = ChoiceOption.class),
        @XmlElement(name = "exampleOption", type = ExampleOption.class),
        @XmlElement(name = "fileOption", type = FileOption.class)
    })
    protected List<Option> options;
    @XmlAttribute(name = "displayName", required = true)
    protected String displayName;

    /**
     * Gets the value of the options property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the options property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringOption }
     * {@link NumberOption }
     * {@link BooleanOption }
     * {@link ChoiceOption }
     * {@link ExampleOption }
     * {@link FileOption }
     * 
     * 
     */
    public List<Option> getOptions() {
        if (options == null) {
            options = new ArrayList<Option>();
        }
        return this.options;
    }

    /**
     * 
     * The name for this option group to be shown to the user.
     *       
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

}
