//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 03:44:23 PM EST 
//


package edu.cmu.cs.diamond.opendiamond.bundle;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PredicateSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PredicateSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="options" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}OptionList" minOccurs="0"/>
 *         &lt;element name="filters" type="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}FilterList"/>
 *       &lt;/all>
 *       &lt;attribute name="displayName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PredicateSpec", propOrder = {

})
public class PredicateSpec {

    @XmlElement(name = "options")
    protected OptionList optionList;
    @XmlElement(name = "filters", required = true)
    protected FilterList filterList;
    @XmlAttribute(name = "displayName", required = true)
    protected String displayName;

    /**
     * 
     * A list of options to be displayed in the user interface.  May include either
     * option groups or individual options, but not both.
     *           
     * 
     * @return
     *     possible object is
     *     {@link OptionList }
     *     
     */
    public OptionList getOptionList() {
        return optionList;
    }

    /**
     * Sets the value of the optionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionList }
     *     
     */
    public void setOptionList(OptionList value) {
        this.optionList = value;
    }

    /**
     * 
     * A description of the filters to instantiate when performing a search.
     *           
     * 
     * @return
     *     possible object is
     *     {@link FilterList }
     *     
     */
    public FilterList getFilterList() {
        return filterList;
    }

    /**
     * Sets the value of the filterList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterList }
     *     
     */
    public void setFilterList(FilterList value) {
        this.filterList = value;
    }

    /**
     * 
     * The predicate or codec name to be shown to the user.
     *       
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

}
