//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 03:44:23 PM EST 
//


package edu.cmu.cs.diamond.opendiamond.bundle;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * A string option, displayed in the user interface as a single-line or
 * multi-line text field.
 *     
 * 
 * <p>Java class for StringOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StringOption">
 *   &lt;complexContent>
 *     &lt;extension base="{http://diamond.cs.cmu.edu/xmlns/opendiamond/bundle-1}Option">
 *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="multiLine" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" default="20" />
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" default="4" />
 *       &lt;attribute name="initiallyEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="disabledValue" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StringOption")
public class StringOption
    extends Option
{

    @XmlAttribute(name = "default")
    protected String _default;
    @XmlAttribute(name = "multiLine")
    protected Boolean multiLine;
    @XmlAttribute(name = "width")
    protected Integer width;
    @XmlAttribute(name = "height")
    protected Integer height;
    @XmlAttribute(name = "initiallyEnabled")
    protected Boolean initiallyEnabled;
    @XmlAttribute(name = "disabledValue")
    protected String disabledValue;

    /**
     * 
     * The initial value of the option.
     *           
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefault() {
        if (_default == null) {
            return "";
        } else {
            return _default;
        }
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefault(String value) {
        this._default = value;
    }

    /**
     * 
     * Whether to use a multi-line input field in the user interface.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMultiLine() {
        if (multiLine == null) {
            return false;
        } else {
            return multiLine;
        }
    }

    /**
     * Sets the value of the multiLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiLine(Boolean value) {
        this.multiLine = value;
    }

    /**
     * 
     * The width of the multi-line input field in characters.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWidth() {
        if (width == null) {
            return  20;
        } else {
            return width;
        }
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidth(Integer value) {
        this.width = value;
    }

    /**
     * 
     * The height of the multi-line input field in characters.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHeight() {
        if (height == null) {
            return  4;
        } else {
            return height;
        }
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * 
     * If specified, the option can be disabled by the user, and the initial
     * enablement is as specified.
     *           
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInitiallyEnabled() {
        return initiallyEnabled;
    }

    /**
     * Sets the value of the initiallyEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInitiallyEnabled(Boolean value) {
        this.initiallyEnabled = value;
    }

    /**
     * 
     * The value returned if the option is disabled by the user.
     *           
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisabledValue() {
        if (disabledValue == null) {
            return "";
        } else {
            return disabledValue;
        }
    }

    /**
     * Sets the value of the disabledValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisabledValue(String value) {
        this.disabledValue = value;
    }

}
